// Environment variable configuration for Expo
// In Expo, environment variables must be prefixed with EXPO_PUBLIC_ to be accessible in the client

export const Config = {
  // Firebase Configuration
  FIREBASE_API_KEY: process.env.EXPO_PUBLIC_FIREBASE_API_KEY,
  FIREBASE_AUTH_DOMAIN: process.env.EXPO_PUBLIC_FIREBASE_AUTH_DOMAIN,
  FIREBASE_DATABASE_URL: process.env.EXPO_PUBLIC_FIREBASE_DATABASE_URL,
  FIREBASE_PROJECT_ID: process.env.EXPO_PUBLIC_FIREBASE_PROJECT_ID,
  FIREBASE_STORAGE_BUCKET: process.env.EXPO_PUBLIC_FIREBASE_STORAGE_BUCKET,
  FIREBASE_MESSAGING_SENDER_ID: process.env.EXPO_PUBLIC_FIREBASE_MESSAGING_SENDER_ID,
  FIREBASE_APP_ID: process.env.EXPO_PUBLIC_FIREBASE_APP_ID,
  FIREBASE_MEASUREMENT_ID: process.env.EXPO_PUBLIC_FIREBASE_MEASUREMENT_ID,

  // API Configuration
  API_URL: process.env.EXPO_PUBLIC_API_URL,
  USDA_API_KEY: process.env.EXPO_PUBLIC_USDA_API_KEY,
  USDA_BASE_URL: process.env.EXPO_PUBLIC_USDA_BASE_URL,

  // Contact Information
  CONTACT_EMAIL: process.env.EXPO_PUBLIC_CONTACT_EMAIL
};
